#!/bin/bash

JAVA_HOME=$HOME/etc/soft/jdk1.8.0_45
pid=server/target/universal/stage/RUNNING_PID
port1=9003
port2=9004
NICE=19
myfleet_base=$HOME/service/MyFleetGirls

# pull
cd $myfleet_base/9003 && git --git-dir=.git pull
cd $myfleet_base/9004 && git --git-dir=.git pull

if [ `netstat -ant | grep ":$port1" | wc -l` -gt 0 ]
then
    port=$port2
    kill_port=$port1
else
    port=$port1
    kill_port=$port2
fi

# Directory
myfleet_dir=$myfleet_base/$port
cd $myfleet_dir

# Kill old process
kill `cat $pid`

#
nice -n $NICE sbt -java-home $JAVA_HOME assembly
if [ "`md5sum server/public/client/MyFleetGirls.jar | cut -d " " -f1`" != "`md5sum  client/target/scala-2.11/MyFleetGirls.jar | cut -d " " -f1`" ]; then
    mv server/public/zip/MyFleetGirls.zip server/public/zip/MyFleetGirls.zip.old
    mv server/public/client/MyFleetGirls.jar.pack.gz server/public/client/MyFleetGirls.jar.pack.gz.old
    nice -n $NICE zip -j server/public/zip/MyFleetGirls.zip update/target/update.jar LICENSE update/update.properties update/myfleetgirls.keystore package/resources/application.conf.sample package/resources/MyFleetGirls.bat package/resources/MyFleetGirls.sh package/resources/MyFleetGirls.command package/resources/IE_PROXY.REG
    cp LICENSE MyFleetGirls.bat MyFleetGirls.sh MyFleetGirls.command update/update.properties update/myfleetgirls.keystore package/resources/application.conf.sample package/resources/IE_PROXY.REG client/target/scala-2.11/MyFleetGirls.jar server/public/client/
    nice -n $NICE pack200 --unknown-attribute=pass server/public/client/MyFleetGirls.jar.pack.gz server/public/client/MyFleetGirls.jar 2> /dev/null
fi

nice -n $NICE /mnt/backup/service/dump/myfleet/dump.sh
nice -n $NICE sbt -java-home $JAVA_HOME stage
sleep 3
JAVA_HOME=$JAVA_HOME server/target/universal/stage/bin/myfleetgirlsserver -J-Xms1G -J-Xmx2G -J-Xloggc:$myfleet_dir/gc.log -J-XX:+PrintGCDetails -J-XX:+PrintGCDateStamps -J-XX:+HeapDumpOnOutOfMemoryError -Dhttp.port=$port &

sleep 10
echo "Kill old process"
kill `cat ../$kill_port/$pid`
