
insert into cell_info values
    (2, 4, 12, 'I', false, false),
    (2, 4, 16, 'J', false, true),
    (2, 4, 18, 'J', false, true),
    (6, 1, 1, 'G', true, false),
    (6, 1, 2, 'A', true, false),
    (6, 1, 3, 'B', true, false),
    (6, 1, 4, 'C', false, false),
    (6, 1, 5, 'D', false, false),
    (6, 1, 6, 'E', false, false),
    (6, 1, 7, 'H', false, false),
    (6, 1, 8, 'F', false, false),
    (6, 1, 9, 'I', false, false),
    (6, 1, 10, 'J', false, false),
    (6, 1, 11, 'K', false, true),
    (6, 1, 12, 'D', false, false),
    (6, 1, 13, 'D', false, false),
    (6, 2, 2, 'B', true, false),
    (6, 2, 5, 'E', false, false),
    (6, 2, 6, 'F', false, false),
    (6, 2, 9, 'H', false, false),
    (6, 2, 10, 'I', false, false),
    (6, 2, 13, 'D', false, false),
    (6, 2, 17, 'K', false, true);
