
insert into cell_info values
    (1, 6, 1, 'A', true, false),
    (1, 6, 2, 'C', true, false),
    (1, 6, 3, 'E', false, false),
    (1, 6, 4, 'G', false, false),
    (1, 6, 5, 'H', false, false),
    (1, 6, 6, 'K', false, false),
    (1, 6, 7, 'M', false, false),
    (1, 6, 8, 'L', false, false),
    (1, 6, 9, 'J', false, false),
    (1, 6, 10, 'I', false, false),
    (1, 6, 11, 'D', false, false),
    (1, 6, 12, 'F', false, false),
    (1, 6, 13, 'B', false, false),
    (1, 6, 14, 'N', false, true),
    (1, 6, 15, 'K', false, false),
    (1, 6, 16, 'D', false, false),
    (1, 6, 17, 'N', false, true),
    (5, 5, 9, 'I', false, false),
    (5, 5, 14, 'N', false, true);
